# Generated by Django 3.0.4 on 2020-04-29 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('mtr_id', models.AutoField(primary_key=True, serialize=False)),
                ('mtr_title', models.CharField(max_length=32)),
                ('mtr_description', models.CharField(max_length=32)),
                ('mtr_views', models.PositiveIntegerField()),
                ('mtr_website', models.URLField()),
                ('mtr_display_order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('trk_id', models.AutoField(primary_key=True, serialize=False)),
                ('trk_title', models.CharField(max_length=32)),
                ('trk_description', models.CharField(max_length=256)),
                ('trk_views', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_username', models.CharField(max_length=32, unique=True)),
                ('usr_password_hash', models.CharField(max_length=64)),
                ('usr_email', models.EmailField(max_length=254, unique=True)),
                ('usr_location', models.CharField(max_length=64)),
                ('usr_website', models.URLField(null=True)),
                ('usr_work', models.CharField(max_length=64)),
                ('usr_education', models.CharField(max_length=64)),
                ('usr_skills', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TrackRating',
            fields=[
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
                ('tr_rating', models.PositiveIntegerField()),
                ('tr_trk_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opentrack_app.Track')),
                ('tr_usr_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opentrack_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='TrackFavorite',
            fields=[
                ('tf_id', models.AutoField(primary_key=True, serialize=False)),
                ('tf_trk_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opentrack_app.Track')),
                ('tf_usr_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opentrack_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='trk_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opentrack_app.User'),
        ),
        migrations.CreateModel(
            name='MaterialRating',
            fields=[
                ('mr_id', models.AutoField(primary_key=True, serialize=False)),
                ('mr_rating', models.PositiveIntegerField()),
                ('mr_mtr_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opentrack_app.Material')),
                ('mr_usr_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opentrack_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialFavorite',
            fields=[
                ('mf_id', models.AutoField(primary_key=True, serialize=False)),
                ('mf_mtr_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opentrack_app.Material')),
                ('mf_usr_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opentrack_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='mtr_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opentrack_app.Track'),
        ),
    ]
