# Generated by Django 3.0.4 on 2020-04-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opentrack_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usr_image_relative_path',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
